clc;
clear all;
a=input('Enter coefficients of output variables ');
b=input('Enter coefficients of input variables ');
n=input('Enter the number of samples ');
[h,t]=impz(b,a,n);
figure;
plot(t,h);
grid on;
xlabel('t');
ylabel('h(t)');
title('Impulse Response in Continious Time Domain');
figure;
stem(t,h,'m');
xlabel('n');
ylabel('h(n)');
title('Impulse Response in Discrete Time Domain');
grid on;
figure;
subplot(2,1,1),plot(t,h);
xlabel('t');
ylabel('h(t)');
title('Impulse Response in Continous Time Domain');
subplot(2,1,2),stem(t,h,'m');
xlabel('n');
ylabel('h(n)');
title('Impulse Response in Discrete Time Domain');